export default {
  SET_HEROES_DISPLAY: 'SET_HEROES_DISPLAY',
  SET_ACTUAL_PAGE: 'SET_ACTUAL_PAGE',
  SET_SEARCH_TXT: 'SET_SEARCH_TXT',
  ADD_HERO: 'ADD_HERO',
  UPDATE_HERO: 'UPDATE_HERO',
  DELETE_HERO: 'DELETE_HERO',
};
